#!/usr/bin/env python2
import zlib
import argparse
from fw_web_up import FwWebUp
from kaitaistruct import KaitaiStream

parser = argparse.ArgumentParser()
parser.add_argument('file', help='sysa-dl file')
parser.add_argument("out", help="unpacked hdd ext2 file")
args = parser.parse_args()

fw = FwWebUp.from_file(args.file)
for s in fw.sections.section:
    if s.head.name.content == "sysa_gzip":
        dec = zlib.decompressobj(32 + zlib.MAX_WBITS)
        hdd = dec.decompress(s.data)
        with open(args.out, "wb") as fd:
            fd.write(hdd)
